spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_star
    username: admin_db
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 9008